#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum custom_keycodes {
  TMUX_PASTE,
  TMUX_BMENU,
  TMUX_CMODE,
};



const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x5_3(
		    KC_QUOT,         KC_COMM,        KC_DOT,         KC_P,     KC_Y,    			KC_F,      KC_G,         KC_C,         KC_R,         KC_L,
		    KC_A,            KC_O,           KC_E,           KC_U,     KC_I,				KC_D,      KC_H,         KC_T,         KC_N,         KC_S,
		    LALT_T(KC_SCLN), LGUI_T(KC_Q), LSFT_T(KC_J), LCTL_T(KC_K), KC_X, 				KC_B,      RCTL_T(KC_M), RSFT_T(KC_W), RGUI_T(KC_V), RALT_T(KC_Z),
		                                     OSL(2),     KC_BSPC,      LT(1,KC_ESC),			KC_ENT,    KC_SPC,       OSL(2)
    ),

    [1] = LAYOUT_split_3x5_3(
		    LCA(KC_DEL),     KC_TRNS,       LCS(KC_TAB), LCTL(KC_TAB), KC_DEL,				KC_TRNS,   KC_HOME,      KC_PGDN,      KC_PGUP,      KC_END,
		    KC_TRNS,         KC_LALT,       LSFT(KC_TAB),     KC_TAB,  KC_CAPS,				KC_TRNS,   KC_LEFT,      KC_DOWN,      KC_UP,        KC_RGHT,
		    KC_TRNS,         KC_TRNS,       KC_TRNS,   LCTL_T(KC_INS), CW_TOGG,				KC_TRNS,   KC_TRNS,      KC_TRNS,      KC_TRNS,      KC_TRNS,
		    		                    KC_TRNS,     KC_TRNS,      KC_TRNS,				KC_TRNS,   KC_TRNS,      KC_TRNS
    ),

    [2] = LAYOUT_split_3x5_3(
		    KC_TRNS,         TMUX_PASTE,       KC_LBRC,      KC_RBRC,     KC_TRNS,				KC_BSLS,   KC_7,         KC_8,         KC_9,         KC_EQL,
		    TMUX_BMENU,         TMUX_CMODE,       KC_LPRN,      KC_RPRN,     KC_TRNS,				KC_SLSH,   KC_4,         KC_5,         KC_6,         KC_MINS,
		    KC_TRNS,   LGUI_T(KC_GRV), LSFT_T(KC_BSLS), LCTL_T(KC_SLSH), KC_TRNS,			KC_0,      RCTL_T(KC_1), RSFT_T(KC_2), RGUI_T(KC_3), RALT_T(KC_DOT),
		                                    KC_TRNS,     KC_TRNS,      KC_TRNS,				KC_TRNS,   KC_TRNS,      KC_TRNS
		    ),

    [3] = LAYOUT_split_3x5_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, UG_HUEU, UG_SATU, UG_VALU, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, UG_HUED, UG_SATD, UG_VALD, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LGUI, KC_SPC, KC_TRNS, KC_TRNS, KC_ENT, KC_RALT),
    [4] = LAYOUT_split_3x5_3(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};

const char chordal_hold_layout[MATRIX_ROWS][MATRIX_COLS] PROGMEM = LAYOUT_split_3x5_3(
  'L', 'L', 'L', 'L', 'L',
  'L', 'L', 'L', 'L', 'L',
  'L', 'L', 'L', 'L', 'L',
  '*', '*', '*',
  'R', 'R', 'R', 'R', 'R',
  'R', 'R', 'R', 'R', 'R',
  'R', 'R', 'R', 'R', 'R',
  '*', '*', '*'
);


bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) {
    case TMUX_PASTE:
    if (record->event.pressed) {
      SEND_STRING(SS_LCTL(SS_TAP(X_B))SS_DELAY(100)  SS_TAP(X_RBRC));
    }
    break;
    case TMUX_BMENU:
    if (record->event.pressed) {
      SEND_STRING(SS_LCTL(SS_TAP(X_B))SS_DELAY(100)  SS_TAP(X_EQL));
    }
    break;
    case TMUX_CMODE:
    if (record->event.pressed) {
      SEND_STRING(SS_LCTL(SS_TAP(X_B))SS_DELAY(100)  SS_TAP(X_LBRC));
    }
    break;

  }
  return true;
}


#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C


